-- 배추, 3000g , 10000원, 홈플러스 , 강남점, 1000평, 주차장 500석
-- 무, 500g, 5000원, 홈플러스, 종로점, 500평, 주차장 300석
-- 배추, 2000g,5000원, 이마트, 서초점, 800평, 주차장 800석

--DROP TABLE MARKET CASCADE CONSTRAINTS PURGE;
--DROP SEQUENCE MARKET_SEQ;
--DROP TABLE PRODUCT CASCADE CONSTRAINTS PURGE;
--DROP SEQUENCE PRODUCT_SEQ;


CREATE TABLE MARKET(
  M_NO NUMBER(2) PRIMARY KEY,
  M_NAME VARCHAR2(15 CHAR) NOT NULL,
  M_LOCATION VARCHAR2(5 CHAR) NOT NULL,
  M_SPACE NUMBER(4) NOT NULL,
  M_PARK NUMBER(3) NOT NULL
);

CREATE SEQUENCE MARKET_SEQ;

INSERT INTO MARKET VALUES(MARKET_SEQ.NEXTVAL,'홈플러스','강남',1000,500);
INSERT INTO MARKET VALUES(MARKET_SEQ.NEXTVAL,'홈플러스','종로',500,300);
INSERT INTO MARKET VALUES(MARKET_SEQ.NEXTVAL,'이마트','서초',800,800);

CREATE TABLE PRODUCT(
  P_NO NUMBER(2) PRIMARY KEY,
  P_NAME VARCHAR2(15 CHAR) NOT NULL,
  P_WEIGHT NUMBER(4) NOT NULL,
  P_PRICE NUMBER(5) NOT NULL,
  P_M_NO NUMBER (2) NOT NULL,
  CONSTRAINT FK_P_M_NO FOREIGN KEY(P_M_NO)
  REFERENCES MARKET(M_NO)
  ON DELETE CASCADE
);

CREATE SEQUENCE PRODUCT_SEQ;

INSERT INTO PRODUCT VALUES(PRODUCT_SEQ.NEXTVAL,'배추',3000,10000,1);
INSERT INTO PRODUCT VALUES(PRODUCT_SEQ.NEXTVAL,'무',500,5000,2);
INSERT INTO PRODUCT VALUES(PRODUCT_SEQ.NEXTVAL,'배추',2000,5000,3);


--C - INSERT 
--R - SELECT
--U - UPDATE
UPDATE 테이블명
    SET 컬럼명 = 값, 컬럼명 = 값, ...  --바꿀 내용
    WHERE 조건식;
    
--무를 공짜로    
UPDATE PRODUCT SET P_PRICE = 0
WHERE P_NAME = '무';
SELECT * FROM PRODUCT;

--배추를 김장용특대배추로 수정
UPDATE PRODUCT SET P_NAME = '김장용특대배추' 
WHERE P_NAME = '배추';
SELECT * FROM PRODUCT;

--전 마트의 주차장 30% 줄이기
UPDATE MARKET SET M_PARK = M_PARK*0.7 ;
SELECT * FROM MARKET;

--홈플러스 종로점의 상품들 가격 10% 할인
UPDATE PRODUCT SET P_PRICE = P_PRICE*0.9
WHERE P_M_NO = 
(SELECT M_NO FROM MARKET WHERE M_NAME='홈플러스' AND M_LOCATION='종로');
SELECT * FROM MARKET;

--제일 비싼 상품 10% 할인
UPDATE PRODUCT SET P_PRICE = P_PRICE*0.9 
WHERE P_PRICE = (SELECT MAX(P_PRICE) FROM PRODUCT);

--D - DELETE
DELETE FROM 테이블명
   WHERE 조건식;
   
-- 무 삭제
DELETE FROM PRODUCT
    WHERE p_name='무';

-- 가장 좁은 매장 상품 다 삭제
DELETE FROM PRODUCT WHERE p_m_no = 
(SELECT m_no FROM MARKET WHERE m_space =
(SELECT MIN(m_space) FROM MARKET));
